name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  test:
    name: Test ${{ matrix.node }} on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [22, 24]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: ${{ matrix.node }}

      - name: Run E2E tests
        run: pnpm run test
        env:
          PAT_1: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: "rickstaa"

  code-checks:
    name: Code checks

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Format
        run: pnpm run format:check

      - name: Lint (knip)
        run: pnpm run lint:knip
